config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'pages#index'
  

  get '/home' => 'pages#home'

  get '/user/:id' => 'pages#profile'

  get '/explore' => 'pages#explore'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 } #messages are capped at 140 chars.
  default_scope -> {order(created_at: :desc) } #newest posts first.
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # always use protection
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
  end

end

app/controllers/pages_controller.rb
#contains all the code for any page inside /pages
class PagesController < ApplicationController
  #backend code for pages/index
  def index

  end
  #backend code for pages/home
  def home
    @posts = Post.all
    @newPost = Post.new
  end
  #backend code for pages/profile
  def profile
    if(User.find_by_username(params[:id]))
      @username = params[:id]
    else
      redirect_to root_path, :notice=> "User not found!"
    end
    @posts = Post.all.where("user_id = ?", User.find_by_username(params[:id]).id)
    @newPost = Post.new
  end
  #backend code for pages/explore
  def explore
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        respond_to do |f|
            if(!@post.save)
                f.html {redirect_to "/home", notice: "Post created!" }
            else
                f.html {redirect_to "/home", notice: "Error: Post not saved." }
            end
        end
    end
    private
    def post_params
        params.require(:post).permit(:user_id, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/_nav.html.erb
<% if !user_signed_in? %>
    <%= render '/layouts/nav_guest' %>
<% else %>
    <%= render '/layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/home">Home</a></li>
        <li><a href="/home">Moments</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Help</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<a name="top"></a>
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <img class="navbar-brand" src="flutter.jpeg" />
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/home">Home</a></li>
        <li><a href="/home">Moments</a></li>
        <li><a href="/home">Notifications</a></li>
        <li><a href="/home">Messages</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search Flutter">
            </div>
          </form>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="/default.png" class="rounded-img" height="25px" width="25px"></a>
          <ul class="dropdown-menu">
            <li><a href="/user/<%= current_user.username %>">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Edit Profile', edit_user_registration_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          </ul>
          <li type="button" class="btn btn-primary navbar-btn">Add Post</li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flutter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/layouts/nav' %>
  <div class="container">
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/explore.html.erb
<div class="col-xs-6">
    <% for @p in @posts %>
    <div class="panel panel-default">
        <div class="panel-body">
            <p><%= @p.content %></p>
        </div>
    </div>
    <% end %>
</div>

app/views/pages/home.html.erb
<div class="row">
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-image hide-panel-body">
            <img src="/banner.jpg" class="panel-image-preview"></img>
          </div>
          <div class="panel-footer text-center">
            <div class="row">
              <div class="col-sm-2">
                <img src="/default.png" height="50px" width="50px" class="rounded-img"></img>
              </div>
              <div class="col-sm-10">
                <h4>Username</h4>
              </div>
              <div class="col-sm-12" style="margin-top:10px;">
                <div class="col-sm-6" style="font-size: 80%; opacity: .7;">TWEETS<br>
                  <h6 style="color: #286090; font-size: 200%">17</h6>
                </div>
                <div class="col-sm-6" style="font-size: 80%; opacity: .7;">FOLLOWERS<br>
                  <h6 style="color: #286090; font-size: 200%">32</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <h5 style="color: grey; font-size: 125%;">Trends</h5>
                <a href="#">#Trend1</a><br>
                  <span style="color: grey;">31k posts</span><br><br>
                <a href="#">#Trend2</a><br>
                  <span style="color: grey;">25k posts</span><br><br>
                <a href="#">#Trend3</a><br>
                  <span style="color: grey;">8k posts</span><br><br>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <%= render '/components/post_form' %><br><br>
        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
            <div class="panel-body row">
                <div class="col-sm-1">
                    <img src="/default.png" class="rounded-img" height="50px" width="50px"> </img>
                </div>
                <div class="col-sm-11">
                    <p class="post-title"><span class="post-owner"><%= User.find(@p.user_id).username %></span><span class="post-creation"> - <%= @p.created_at.to_formatted_s(:short) %></p></span>
                    <p class="post-content"><%= @p.content %></p>
                </div>
                <div class="col-sm-12">
                    <p class="post-links">
                        <span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>  
                        <a href="#">View Conversation</a>
                    </p>
                </div>
            </div>
        </div>
        <% end %>
        <div class="panel panel-default post-panel">
            <div class="panel-body row">
                <div class="col-sm-12">
                    <center>
                        <img src="flutter.jpeg" height="25" width="25"></img>
                        <a href="#top"><p stlye="opacity: .7; color:grey;">Back to Top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a>
                    </center>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-3">
         <div class="panel panel-default">
            <div class="panel-body">
                <p style="opacity: 0.5;font-size:85%">© 2018 Flutter  About  Help  Center  Terms  Privacy policy  Cookies  Ads info  Brand  Blog  Status  Apps  Jobs  Marketing  Businesses  Developers</p>
            </div>
        </div>
    </div>
</div>

app/views/pages/index.html.erb
<% if !user_signed_in? %>
    <style>
        body{
            background: linear-gradient(
                rgba(0,0,0,0.7),
                rgba(0,0,0,0.7)
            ), url('/background.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        h1{
            color: white;
            font-weight: bold;
        }
        .container-index{
            margin-right: 15%;
            margin-left: 15%;
        }
        .text{
            color: white;
            font-weight: 300;
            font-size: 150%;
        }
        .footer-links{
            text-align: center;
            color: white;
            margin-top: 20%;
            font-size: 75%;
            word-spacing: 8px;
        }
        .log-in{
            float: right;
            width: 300px;
            height:150px;
            margin-top: 7.5%;
        }
        .sign-up{
            float: right;
            width: 300px;
            height: 250px;
        }
    </style>
    <div class="container-index row">
        <div class="col-sm-6">
            <h1>Welcome to Flutter.</h1>
            <p class="text">
                Connect with your friends. Chat with new friends. Share your adventures. <br />
                Such fancy, Much happy.
            </p>
        </div>
        <div class="col-sm-6">
            <div class="log-in panel">
                <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                    <div class="field-top">
                        <%= f.email_field :email, autofocus: true, autocomplete: "email",placeholder: "Email" %>
                    </div>
    
                    <div class="field-top">
                        <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
                    </div>
    
                    <% if devise_mapping.rememberable? -%>
                        <div class="field-top">
                            <%= f.check_box :remember_me %>
                            <%= f.label :remember_me %>
                        </div>
                    <% end -%>
    
                    <div class="actions">
                        <%= f.submit "Log in",class:"btn btn-primary navbar-btn" %>
                    </div>
                <% end %>
            </div>
            <div class="sign-up panel">
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                    <%= devise_error_messages! %>
                    <div class="field">
                        <%= f.text_field :username, autofocus: true, placeholder: "Username" %>
                    </div>
                    <div class="field">
                        <%= f.email_field :email, autocomplete: "email", placeholder: "Email" %>
                    </div>
                    <div class="field">
                        <% if @minimum_password_length %>
                            <em>(<%= @minimum_password_length %> characters minimum)</em>
                        <% end %>
                        <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
                    </div>
    
                    <div class="field">
                        <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Password Confirmation" %>
                    </div>
    
                    <div class="actions">
                        <%= f.submit "Sign up",class:"btn btn-primary navbar-btn" %>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="col-sm-12">
            <p class="footer-links">
                About Help Blog Status Jobs Terms Privacy Ads Brand Apps Advertise Marketing Businesses Developers Directory Settings ©2018Flutter
            </p>
        </div>
       
    </div>
<% else %>
    <script>document.location = "/home";</script>
<% end %>

app/views/pages/profile.html.erb
<div class="row">
    <div class="col-xs-12">
        <div class="jumbotron" style="background-color: #E8E6E8;">
            <%= current_user.username %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>profile</p>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <%= render "/components/post_form" %>
        <% for @p in @posts %>
        <div class="panel panel-default">
            <div class="panel-body">
                <p><%= @p.content %></p>
            </div>
        </div>
        <% end %>
    </div>
    <div class="col-xs-3">
         <div class="panel panel-default">
            <div class="panel-body">
                <p>who to follow</p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <p>trends</p>
            </div>
        </div>
    </div>
</div>